spring:
  application:
    name : 22-tenten-be
  datasource:
    url: ${MYSQL_URL}
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

aws:
  region: ap-northeast-2
  accessKeyId: ${AWS_ACCESS_KEY}
  secretAccessKey: ${AWS_SECRET_KEY}
  s3:
    bucket: ${BUCKET_NAME}
    expiration-time: 300
    max-file-size: 10485760

server:
  forward-headers-strategy: framework
  
app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: kakaobase
    audience: web
    access:
      expiration-time: 1800000 # 30분
    refresh:
      expiration-time: 604800000 # 7일
      token-name: kakaobase_refresh_token
      path: api/auth/tokens

ai:
  server:
    url: ${AI_SERVER_URL}
