spring:
  config:
    activate:
      on-profile: dev
app:
  jwt:
    secure: true
    refresh:
      domain: ${COOKIE_DOMAIN}
      same-site: None

logging:
  level:
    com.kakaobase.snsapp.domain.posts.scheduler: DEBUG
    com.amazonaws.util.EC2MetadataUtils: ERROR
    com.amazonaws.services.s3: INFO
    com.kakaobase.snsapp.domain.auth: DEBUG
    com.kakaobase.snsapp.domain.posts: DEBUG
    org.hibernate.SQL: debug
    # WebSocket 에러 로그 도배 방지를 위한 보안 관련 로그 레벨 조정
    com.kakaobase.snsapp.global.security: WARN
    org.springframework.security: WARN
    org.apache.juli: OFF
    org.apache.catalina: WARN
    org.apache.tomcat: WARN
  discord:
    webhook-url: ${DISCORD_ERROR_WEBHOOK_URL}
    config: classpath:logback-spring.xml