name: Backend - CI/CD (prod)

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '**/README*'

jobs:
  ci:
    name: CI (Build)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build Spring Project
        run: ./gradlew build -x test

  cd:
    name: CD (Push Image & Deploy to EC2)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # AWS CLI & 권한 세팅
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2   # 리전 맞게 수정

      # ECR 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Docker build & push
      - name: Build, Tag, and Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: kakaobase-backend
          IMAGE_TAG: prod
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # EC2 배포 (SSH)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}

            docker pull ${{ steps.login-ecr.outputs.registry }}/kakaobase-backend:prod

            docker stop backend || true
            docker rm backend || true

            # 환경 변수는 SSM Parameter Store에서 주입
            export AI_SERVER_URL=$(aws ssm get-parameter --name "/kakaobase/prod/AI_SERVER_URL" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2)
            export AWS_ACCESS_KEY=$(aws ssm get-parameter --name "/kakaobase/prod/AWS_ACCESS_KEY" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2)
            export AWS_SECRET_KEY=$(aws ssm get-parameter --name "/kakaobase/prod/AWS_SECRET_KEY" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2)
            export AWS_REGION=$(aws ssm get-parameter --name "/kakaobase/prod/AWS_REGION" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2)
            export BUCKET_NAME=$(aws ssm get-parameter --name "/kakaobase/prod/BUCKET_NAME" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2)
            export COOKIE_DOMAIN=$(aws ssm get-parameter --name "/kakaobase/prod/COOKIE_DOMAIN" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2)

            docker run -d --name backend \
              -p 8080:8080 \
              -e AI_SERVER_URL=$(aws ssm get-parameter --name "/kakaobase/prod/AI_SERVER_URL" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e AWS_ACCESS_KEY=$(aws ssm get-parameter --name "/kakaobase/prod/AWS_ACCESS_KEY" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e AWS_REGION=$(aws ssm get-parameter --name "/kakaobase/prod/AWS_REGION" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e AWS_SECRET_KEY=$(aws ssm get-parameter --name "/kakaobase/prod/AWS_SECRET_KEY" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e BUCKET_NAME=$(aws ssm get-parameter --name "/kakaobase/prod/BUCKET_NAME" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e COOKIE_DOMAIN=$(aws ssm get-parameter --name "/kakaobase/prod/COOKIE_DOMAIN" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e DISCORD_ERROR_WEBHOOK_URL=$(aws ssm get-parameter --name "/kakaobase/prod/DISCORD_ERROR_WEBHOOK_URL" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e EMAIL=$(aws ssm get-parameter --name "/kakaobase/prod/EMAIL" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e EMAIL_PASSWORD=$(aws ssm get-parameter --name "/kakaobase/prod/EMAIL_PASSWORD" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e JWT_SECRET=$(aws ssm get-parameter --name "/kakaobase/prod/JWT_SECRET" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e MYSQL_PASSWORD=$(aws ssm get-parameter --name "/kakaobase/prod/MYSQL_PASSWORD" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e MYSQL_URL=$(aws ssm get-parameter --name "/kakaobase/prod/MYSQL_URL" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e REDIS_URL=$(aws ssm get-parameter --name "/kakaobase/prod/REDIS_URL" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e SPRING_DATASOURCE_PASSWORD=$(aws ssm get-parameter --name "/kakaobase/prod/SPRING_DATASOURCE_PASSWORD" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e SPRING_DATASOURCE_URL=$(aws ssm get-parameter --name "/kakaobase/prod/SPRING_DATASOURCE_URL" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e SPRING_DATASOURCE_USERNAME=$(aws ssm get-parameter --name "/kakaobase/prod/SPRING_DATASOURCE_USERNAME" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              -e SPRING_PROFILES_ACTIVE=$(aws ssm get-parameter --name "/kakaobase/prod/SPRING_PROFILES_ACTIVE" --with-decryption --query "Parameter.Value" --output text --region ap-northeast-2) \
              ${{ steps.login-ecr.outputs.registry }}/kakaobase-backend:prod
  

  notify:
    name: Discord Notification
    if: always()
    needs: [ci, cd]
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          CI_RESULT="${{ needs.ci.result || 'skipped' }}"
          CD_RESULT="${{ needs.cd.result || 'skipped' }}"
          
          COLOR="8359053"
          STATUS="⚪ CI/CD 실행됨"
          
          if [ "$CI_RESULT" = "success" ]; then
            STATUS="✅ CI 성공"
            COLOR="5763719"
          elif [ "$CI_RESULT" = "failure" ]; then
            STATUS="❌ CI 실패"
            COLOR="15158332"
          fi
          
          if [ "$CD_RESULT" = "success" ]; then
            STATUS="✅ CD 성공 (EC2 배포 완료)"
            COLOR="3066993"
          elif [ "$CD_RESULT" = "failure" ]; then
            STATUS="❌ CD 실패 (EC2 배포 오류)"
            COLOR="15158332"
          fi
          
          curl -X POST -H "Content-Type: application/json" \
            -d "{
              \"embeds\": [{
                \"title\": \"🔔 GitHub Actions 결과: ${{ github.workflow }}\",
                \"description\": \"$STATUS\n브랜치: \`${{ github.ref_name }}\`\n커밋: \`${{ github.actor }}\`\n[👉 실행 로그 보기](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\",
                \"color\": $COLOR
              }]
            }" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

